version: '3'
services:

  cryptpad:
    image: "promasu/cryptpad:latest"
    hostname: cryptpad

    labels:
      - "traefik.enable=true"
      - traefik.port=3000
      - "traefik.http.routers.${ROUTERNAME}.rule=Host(${DOMAIN})"
      - "traefik.http.routers.${ROUTERNAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTERNAME}.tls.certresolver=myresolver"
    environment:
      - USE_SSL=false
      - STORAGE=./storage/file
      - LOG_TO_STDOUT=true

    restart: always
    volumes:
      - ./data/files:/cryptpad/datastore:rw
      - ./data/customize:/cryptpad/customize:rw
      - ./data/pins:/cryptpad/pins:rw
      - ./data/blob:/cryptpad/blob:rw
      - ./data/blobstage:/cryptpad/blobstage:rw
      - ./data/tasks:/cryptpad/tasks:rw
      - ./data/block:/cryptpad/block:rw
      - ./config.js:/cryptpad/config/config.js:rw
    networks:
      - traefik_network


networks:
  traefik_network:
    external:
      name: traefik_default

